os:
  - linux
language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "iojs-3"
  - "4.0.0"
  - "5.7.0"
  - "6.0.0"
  - "6.9.1"
  - "7.1.0"
  - "10.0.0"
  - "12.0.0"
  - "13"
notifications:
  recipients:
    - 1127132348@qq.com
  email:
    on_success: change
    on_failure: always
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_script: npm run test
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file:
    - releases/*
  skip_cleanup: true
  on:
    branch: master
    tags: true