os:
  - linux
language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "10.0.0"
  - "12.0.0"
  - "13"
notifications:
  email:
    - 1127132348@qq.com
  email:
    on_success: change
    on_failure: always
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_script: yarn build:release && yarn test
deploy:
  provider: releases
  token: ${GH_TOKEN}
  file_glob: true
  file:
    - releases/*
  cleanup: false
  on:
    branch: master
    tags: true