os:
  - linux
language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "10.0.0"
  - "12.0.0"
  - "13"
notifications:
  email:
    recipients:
      - 1127132348@qq.com
    on_success: change
    on_failure: always
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script: node-pre-gyp configure && node-pre-gyp build
script: yarn test
after_script: node-pre-gyp package
deploy:
  provider: releases
  token: ${GH_TOKEN}
  file_glob: true
  skip_cleanup: true
  file:
    - build/stage/**
    - binding.gyp
  on:
    branch: master
    tags: true